 - hosts: servers
   gather_facts: false
   user: vagrant
   become: true
   pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python
   tasks:
    - name: 'Update cache'
      raw: sudo apt-get update

 - hosts: servers
   gather_facts: true
   user: vagrant
   become: true
   roles:
    - role: docker