---
# tasks file for ansible-apache
- name: Update repositories cache and install required pacakges
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

- name: Add Docker repository apt signing key, will not download if present
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu "{{ ansible_distribution_release }}" stable
    state: present
    update_cache: yes

- name: Install Docker
  apt:
    name: docker-ce
    state: latest
    update_cache: yes

- name: Ensure docker users are added to the docker group.
  user:
    name: vagrant
    groups: docker
    append: true

