---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu
    image: ubuntu:xenial
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ANSIBLE0010
scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - destroy
verifier:
  name: inspec
  lint:
    name: rubocop
