---
# This is an example playbook to execute inspec tests.
# Tests need distributed to the appropriate ansible host/groups
# prior to execution by `inspec exec`.

- name: Verify
  hosts: all
  become: true
  vars:
    inspec_bin: /opt/inspec/bin/inspec
    inspec_download_source_dir: /usr/local/src
    inspec_test_directory: /tmp/molecule/inspec
  tasks:
    - name: Setting variables (CentOS 6 / RHEL 6)
      set_fact:
        inspec_download_url: "https://packages.chef.io/files/stable/inspec/3.2.6/el/6/inspec-3.2.6-1.el6.x86_64.rpm"
        inspec_download_sha256sum: 9687bf5134756ae08fe9af978155ab6079f77e899ea6d6ef5038a3b1f7e93350
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

    - name: Setting variables (CentOS 7 / RHEL 7)
      set_fact:
        inspec_download_url: "https://packages.chef.io/files/stable/inspec/3.2.6/el/7/inspec-3.2.6-1.el7.x86_64.rpm"
        inspec_download_sha256sum: d0390ce6eed406695da130a9ecd648cc5ed42aba7b5b5a00ae693b97412719f1
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

    - name: Setting variables (Debian 8 / Ubuntu 14.04)
      set_fact:
        inspec_download_url: "https://packages.chef.io/files/stable/inspec/3.2.6/ubuntu/14.04/inspec_3.2.6-1_amd64.deb"
        inspec_download_sha256sum: 69e5fc9d0495a6b4ea647184d5cad2eaf668b2a21c267abada19c3785765bda2
      when: ansible_os_family == "Debian" and (ansible_distribution_major_version == "8" or ansible_distribution_version == "14.04")

    - name: Setting variables (Debian 8 / Ubuntu 16.04)
      set_fact:
        inspec_download_url: "https://packages.chef.io/files/stable/inspec/3.2.6/ubuntu/16.04/inspec_3.2.6-1_amd64.deb"
        inspec_download_sha256sum: 69e5fc9d0495a6b4ea647184d5cad2eaf668b2a21c267abada19c3785765bda2
      when: ansible_os_family == "Debian" and (ansible_distribution_major_version == "8" or ansible_distribution_version == "16.04")

    - name: Setting variables (Debian 9 / Ubuntu 18.04)
      set_fact:
        inspec_download_url: "https://packages.chef.io/files/stable/inspec/3.2.6/ubuntu/18.04/inspec_3.2.6-1_amd64.deb"
        inspec_download_sha256sum: 69e5fc9d0495a6b4ea647184d5cad2eaf668b2a21c267abada19c3785765bda2
      when: ansible_os_family == "Debian" and (ansible_distribution_major_version == "9" or ansible_distribution_version == "18.04")

    - name: Download Inspec
      get_url:
        url: "{{ inspec_download_url }}"
        dest: "{{ inspec_download_source_dir }}"
        sha256sum: "{{ inspec_download_sha256sum }}"
        mode: 0755

    - name: Install Inspec (apt)
      apt:
        deb: "{{ inspec_download_source_dir }}/{{ inspec_download_url.split('/')[-1] }}"
        state: present
      when: ansible_pkg_mgr == "apt"
    
    - name: Check inspec version
      command: inspec help 
      register: inspecversion
    - debug: var=inspecversion.stdout_lines

    - name: Install Inspec (yum)
      yum:
        name: "{{ inspec_download_source_dir }}/{{ inspec_download_url.split('/')[-1] }}"
        state: latest
      when: ansible_pkg_mgr == "yum"

    - name: Create Molecule directory for test files
      file:
        path: "{{ inspec_test_directory }}"
        state: directory

    - name: Copy Inspec tests to remote
      copy:
        src: "{{ item }}"
        dest: "{{ inspec_test_directory }}/{{ item | basename }}"
      with_fileglob:
        - "{{ lookup('env', 'MOLECULE_VERIFIER_TEST_DIRECTORY') }}/test_*.rb"

    - name: Register test files
      shell: "ls {{ inspec_test_directory }}/test_*.rb"
      register: test_files

    - name: Execute Inspec tests
      command: "{{ inspec_bin }} exec {{ item }}"
      register: test_results
      with_items: "{{ test_files.stdout_lines }}"
      ignore_errors: true

    - name: Display details about the Inspec results
      debug:
        msg: "{{ item.stdout_lines }}"
      with_items: "{{ test_results.results }}"

    - name: Fail when tests fail
      fail:
        msg: "Inspec failed to validate"
      when: item.rc != 0
      with_items: "{{ test_results.results }}"
